"use client";

import "./globals.css";
import "bootstrap-material-design/dist/css/bootstrap-material-design.min.css";
import TopNav from "@/components/TopNav";
import { Toaster } from "react-hot-toast";
import { SessionProvider } from "next-auth/react";
import LayoutProvider from "@/providers/LayoutProvider";
import StoreProvider from "@/providers/StoreProvider";

// export const metadata: Metadata = {
//   title: "Next E-Comm",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <SessionProvider>
        <body>
          <StoreProvider>
            {/* <LayoutProvider> */}
            <TopNav />
            <Toaster />
            {children}
            {/* </LayoutProvider> */}
          </StoreProvider>
        </body>
      </SessionProvider>
    </html>
  );
}
