import "./globals.css";
import type { Metadata } from "next";
import "bootstrap-material-design/dist/css/bootstrap-material-design.min.css"

export const metadata: Metadata = {
  title: "Next E-Comm",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <body>{children}</body>
    </html>
  );
}
